import { Beiruti, Cairo, Tajawal, Zain } from "next/font/google";
import "./globals.css";

const zain = Zain({
  variable: "--font-zain",
  weight: ["200", "300", "400", "700", "800", "900"],
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const tajwal = Tajawal({
  variable: "--font-tajwal",
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
});

const beiruti = Beiruti({
  variable: "--font-beiruti",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body
        className={`${zain.variable} ${cairo.variable} ${tajwal.variable} ${beiruti.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
