import "./globals.css";
import { Beiruti, Cairo, Tajawal, Zain } from "next/font/google";
import { LoadApperanceSettings } from "@/lib/apperance-settings";

const zain = Zain({
  variable: "--font-zain",
  weight: ["200", "300", "400", "700", "800", "900"],
  subsets: ["latin"],
});

const cairo = Cairo({
  variable: "--font-cairo",
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
});

const tajwal = Tajawal({
  variable: "--font-tajwal",
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
});

const beiruti = Beiruti({
  variable: "--font-beiruti",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata = {
  title: "MoboLap Platform",
  description: "Generated by MoboLap Developer",
};

export default async function RootLayout({ children }) {
  const { theme, mode, fontFamily, fontSize } = await LoadApperanceSettings();
  console.log("Apperance: ", { theme, mode, fontFamily, fontSize });
  return (
    <html lang="ar" dir="rtl" className={`${theme} ${mode}`}>
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no"
        />
      </head>
      <body
        className={`${zain.variable} ${cairo.variable} ${tajwal.variable} ${beiruti.variable} antialiased`}
        style={{
          ["--font-family"]: fontFamily,
          ["--font-heading"]: fontSize?.heading,
          ["--font-body"]: fontSize?.body,
          ["--font-small"]: fontSize?.small,
          ["--line-height"]: fontSize?.lineHeight,
        }}
      >
        {children}
      </body>
    </html>
  );
}
