import { Cairo, Tajawal } from "next/font/google";
import "./globals.css";
import MoboLayout from "@/layouts/MoboLayout";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const cairo = Cairo({
  variable: "--font-cairo",
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Mobolap Store",
  description: "Generated by Wael Altyeb",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const direction = locale === "ar" ? "rtl" : "ltr";
  return (
    <html
      lang={locale}
      dir={direction}
      suppressHydrationWarning
      data-scroll-behavior="smooth"
    >
      <body className={`${cairo.variable} antialiased`}>
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <MoboLayout locale={locale}>{children}</MoboLayout>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
