export const Products = [
  {
    id: "m1",
    name: "Galaxy S24 Ultra",
    brand: "Samsung",
    price: 1250000,
    image: "/images/S25-Ultra.webp",
    specs: {
      cpu: "Snapdragon 8 Gen 3",
      screen: "6.8-inch QHD+ AMOLED, 120Hz",
      battery: "5000mAh",
      camera: "200MP + 12MP + 10MP + 10MP",
      os: "Android 14",
    },
    variants: [
      {
        sku: "SKU-GalaxyS24Ultra-12GB-256GB",
        color: "Black",
        price: 1250000,
        ram: "12GB",
        storage: "256GB",
      },
      {
        sku: "SKU-GalaxyS24Ultra-12GB-512GB",
        color: "Titanium Gray",
        price: 1349990,
        ram: "12GB",
        storage: "512GB",
      },
    ],
  },
  {
    id: "m2",
    name: "iPhone 15 Pro",
    brand: "Apple",
    price: 2200010,
    image: "/images/iphone_16pro.png",
    specs: {
      cpu: "A17 Pro",
      screen: "6.1-inch OLED, 120Hz",
      battery: "3274mAh",
      camera: "48MP + 12MP + 12MP",
      os: "iOS 17",
    },
    variants: [
      {
        sku: "SKU-iPhone15Pro-8GB-128GB",
        color: "Blue Titanium",
        price: 2200010,
        ram: "8GB",
        storage: "128GB",
      },
      {
        sku: "SKU-iPhone15Pro-8GB-256GB",
        color: "Natural Titanium",
        price: 2300000,
        ram: "8GB",
        storage: "256GB",
      },
    ],
  },
  {
    id: "l1",
    name: "MacBook Air M3",
    brand: "Apple",
    price: 1350000,
    image: "/images/MacBook Air M3.jpg",
    specs: {
      cpu: "Apple M3",
      screen: "13.6-inch Liquid Retina",
      battery: "Up to 18 hours",
      os: "macOS Sonoma",
      weight: "1.24kg",
    },
    variants: [
      {
        sku: "SKU-MacBookAirM3-8GB-256GB",
        color: "Space Gray",
        price: 1350000,
        ram: "8GB",
        storage: "256GB",
      },
      {
        sku: "SKU-MacBookAirM3-16GB-512GB",
        color: "Starlight",
        price: 1499990,
        ram: "16GB",
        storage: "512GB",
      },
    ],
  },
  {
    id: "l2",
    name: "Dell XPS 15",
    brand: "Dell",
    price: 1890000,
    image: "/images/Dell XPS 15.webp",
    specs: {
      cpu: "Intel Core i7-13700H",
      screen: "15.6-inch 3.5K OLED",
      battery: "86Wh",
      os: "Windows 11",
      gpu: "NVIDIA RTX 4060",
    },
    variants: [
      {
        sku: "SKU-DellXPS15-16GB-512GB",
        color: "Platinum Silver",
        price: 1890000,
        ram: "16GB",
        storage: "512GB",
      },
      {
        sku: "SKU-DellXPS15-32GB-1TB",
        color: "Platinum Silver",
        price: 2100000,
        ram: "32GB",
        storage: "1TB",
      },
    ],
  },
];
