import { Cairo } from "next/font/google";
import "./globals.css";
import MainLayout from "@/layouts/MainLayout";
import { cookies } from "next/headers";

const cairo = Cairo({
  variable: "--font-cairo",
  subsets: ["latin"],
});

export const metadata = {
  title: "Mobolap Platform",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const AllCookies = await cookies();
  const mode = AllCookies.get("mode")?.value || "light";
  console.log("Loaded Mode: ", mode);
  return (
    <html lang="ar" dir="rtl" className={`${mode}`}>
      <body className={`${cairo.variable} antialiased`}>
        <MainLayout>{children}</MainLayout>
      </body>
    </html>
  );
}
