export const SpecsFields = [
  {
    key: "specs.cpu",
    title: "المعالج",
    placeholder: "مثال: Intel i7, Snapdragon 888",
    type: "text",
    feildFor: ["موبايلات"],
  },
  {
    key: "specs.screen",
    title: "حجم الشاشة",
    placeholder: "مثال: 15.6 بوصة, 6.7 انش",
    type: "text",
    feildFor: ["موبايلات", "لاب توب"],
  },
  {
    key: "specs.screenType",
    title: "نوع الشاشة",
    placeholder: "مثال: IPS LCD, AMOLED",
    type: "text",
    feildFor: "موبايلات",
  },
  {
    key: "specs.gpu",
    title: "معالج الرسوميات",
    placeholder: "مثال: NVIDIA RTX 3060, Adreno 660",
    type: "text",
    feildFor: true,
  },
  {
    key: "specs.battery",
    title: "البطارية",
    placeholder: "مثال: 5000 مللي أمبير, 60 واط",
    type: "text",
    feildFor: true,
  },
  {
    key: "specs.fingerprint",
    title: "البصمة",
    placeholder: "مثال: مستشعر بصمة الأصبع",
    type: "text",
    feildFor: true,
  },
  {
    key: "specs.backCamera",
    title: "الكاميرا الخلفية",
    placeholder: "مثال: مستشعر 108 ميجابكسل",
    type: "text",
    feildFor: "موبايلات",
  },
  {
    key: "specs.frontCamera",
    title: "كاميرا السيلفي",
    placeholder: "مثال: مستشعر 32 ميجابكسل",
    type: "text",
    feildFor: true,
  },
  {
    key: "specs.colors",
    title: "الالوان",
    placeholder: "ابيض, اسود, ذهبي, رمادي",
    type: "text",
    feildFor: true,
  },
  {
    key: "specs.model",
    title: "سنة الانتاج",
    placeholder: "مثال: 2021",
    type: "text",
    feildFor: true,
  },
  {
    key: "specs.os",
    title: "نظام التشغيل",
    placeholder: "IOS 18.6",
    type: "text",
    feildFor: true,
  },
  {
    key: "specs.ui",
    title: "واجهة التشغيل",
    placeholder: "مثال: MIUI 14, One UI 5.1",
    type: "text",
    feildFor: "موبايلات",
  },
];
