import { Tajawal } from "next/font/google";
import "./globals.css";
import MoboLayout from "@/layouts/MoboLayout";

const tajawal = Tajawal({
  variable: "--font-tajawal",
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Mobolap Store",
  description: "Generated by Wael Altyeb",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ar" dir="rtl">
      <body className={`${tajawal.variable} antialiased`}>
        <MoboLayout>{children}</MoboLayout>
      </body>
    </html>
  );
}
