import { Tajawal } from "next/font/google";
import "./globals.css";
import MoboLayout from "@/layouts/MoboLayout";
import { ThemeProvider } from "@/components/ui/theme-provider";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";

const tajawal = Tajawal({
  variable: "--font-tajawal",
  weight: ["200", "300", "400", "500", "700", "800", "900"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Mobolap Store",
  description: "Generated by Wael Altyeb",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const direction = locale === "ar" ? "rtl" : "ltr";
  return (
    <html lang={locale} dir={direction} suppressHydrationWarning data-scroll-behavior="smooth">
      <body className={`${tajawal.variable} antialiased`}>
        <NextIntlClientProvider>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <MoboLayout>{children}</MoboLayout>
          </ThemeProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
